# Using hvr's multi-ghc-travis template and ppa. Thanks hvr!!

env:
   - GHCVER=7.10.1
   - GHCVER=8.0.1

before_install:
   - sudo add-apt-repository -y ppa:hvr/ghc
   - sudo apt-get update
   - sudo apt-get install ghc-$GHCVER alex happy
   - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
  - cabal update
  - cabal sandbox init
  - cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests -v2
  - cabal build
  - cabal test
